# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Polygon2Line
                                 A QGIS plugin
 面转线工具，记录拓扑关系
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-28
        copyright            : (C) 2020 by Beamatch
        email                : 2017301110147@whu.edu.cn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Polygon2Line class from file Polygon2Line.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .polygon_to_line import Polygon2Line
    return Polygon2Line(iface)
